version: "3"

services:
  db:
    image: postgres
    container_name: uhomcrm_db
    ports: ["5435:5432"]
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "uhomcrm"
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  web:
    image: uhomcrm-web:latest
    container_name: uhomcrm_web
    ports: [ "8086:8080" ]
    environment:
      SERVER_ADDRESS: "0.0.0.0:8080"
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST: "db"
      POSTGRES_PORT: "5432"
      POSTGRES_DATABASE: "uhomcrm"
    volumes:
      - ./crm/:/app/
    depends_on:
      - db

  twportainer:
    image: portainer/portainer-ce:latest
    container_name: twportainer
    environment:
      - TZ=Europe/Moscow
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
    ports:
      - "9000:9000"
      - "9443:9443"
    restart: always


  pdf:
    image: ultroa13/uhom_crm_pdf:latest
    container_name: uhomcrm_pdf
    ports: [ "8000:8000" ]
    environment:
      SERVER_ADDRESS: "0.0.0.0:8000"
    volumes:
      - ./pdf/:/pdf_routing/

volumes:
  postgres-data:
